config/routes.rb
Ordering::Application.routes.draw do
  post "order/start", :as => :start
  get "order/start", :as => :gstart
  post "order/result", :as => :result

  root 'order#start'

  

end

app/models/order.rb
class Order

  def self.order_jobs(input)
    begin
      msg = Order.valid?(input)
    rescue Exception => ex
      return 'circular dependency' if ex.class == SystemStackError
    end

    return msg unless msg == true

    res = input
    for arr in input do
      i = nil
      i = res.index(res.detect{|d| d[1] == arr[0]})
      res.insert(i, res.delete(arr)) if i
    end

    res
  end

  def self.valid?(input)
    for arr in input do
      return 'depend on itself' if arr[0] == arr[1]
      @@begin = arr
      return 'circular dependency' if Order.circular?(input, arr)
    end
    return true
  end

  def self.circular?(input, job)
    if job[1]
      dep = input.detect{|d| d[0] == job[1]}
      return true if dep == @@begin
      Order.circular?(input, dep)
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/order_controller.rb
class OrderController < ApplicationController
  def start
  end

  def result
    i = 0
    input = []
    (params.count - 5).times do
      i += 1
      job = []
      if params["#{i}"][:job] == ""

      else
        job << params["#{i}"][:job]
        job << params["#{i}"][:dependency] unless params["#{i}"][:dependency] == ""
      end

      input << job unless job == []

    end

    @output = Order.order_jobs(input)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def link_to_remove_fields(name, f)
    f.hidden_field(:_destroy) + link_to_function(name, "remove_fields(this)")
  end

  def link_to_add_fields(name, f, association)
    new_object = f.object.class.reflect_on_association(association).klass.new
    fields = f.fields_for(association, new_object, :child_index => "new_#{association}") do |builder|
      render(association.to_s.singularize + "_fields", :f => builder)
    end
    link_to_function(name, "add_fields(this, \"#{association}\", \"#{escape_javascript(fields)}\")")
  end

  def link_to_add_fields_no_object(name, association)
    new_object = object.class.reflect_on_association(association).klass.new
    fields = fields_for(association, new_object, :child_index => "new_#{association}") do |builder|
      render(association.to_s.singularize + "_fields", :f => builder)
    end
    link_to_function(name, "add_fields(this, \"#{association}\", \"#{escape_javascript(fields)}\")")
  end
end

app/helpers/error_messages_helper.rb
module ErrorMessagesHelper
  # Render error messages for the given objects. The :message and :header_message options are allowed.
  def error_messages_for(*objects)
    options = objects.extract_options!
    options[:header_message] ||= I18n.t(:"activerecord.errors.header", :default => "Invalid Fields")
    options[:message] ||= I18n.t(:"activerecord.errors.message", :default => "Correct the following errors and try again.")
    messages = objects.compact.map { |o| o.errors.full_messages }.flatten
    unless messages.empty?
      content_tag(:div, :class => "error_messages") do
        list_items = messages.map { |msg| content_tag(:li, msg) }
        content_tag(:h2, options[:header_message]) + content_tag(:p, options[:message]) + content_tag(:ul, list_items.join.html_safe)
      end
    end
  end

  module FormBuilderAdditions
    def error_messages(options = {})
      @template.error_messages_for(@object, options)
    end
  end
end

ActionView::Helpers::FormBuilder.send(:include, ErrorMessagesHelper::FormBuilderAdditions)

app/helpers/layout_helper.rb
# These helper methods can be called in your template to set variables to be used in the layout
# This module should be included in all views globally,
# to do so you may need to add this line to your ApplicationController
#   helper :layout
module LayoutHelper
  def title(page_title, show_title = true)
    content_for(:title) { h(page_title.to_s) }
    @show_title = show_title
  end

  def show_title?
    @show_title
  end

  def stylesheet(*args)
    content_for(:head) { stylesheet_link_tag(*args) }
  end

  def javascript(*args)
    content_for(:head) { javascript_include_tag(*args) }
  end
end

app/helpers/order_helper.rb
module OrderHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for?(:title) ? yield(:title) : "Jobs ordering" %></title>
    <%= stylesheet_link_tag "application" %>
    <!--<%= javascript_include_tag "defaults" %>-->
    <%= csrf_meta_tag %>
    <%= yield(:head) %>
  </head>
  <body>
    <div id="container">
      <% flash.each do |name, msg| %>
        <%= content_tag :div, msg, :id => "flash_#{name}" %>
      <% end %>
      <%= content_tag :h1, yield(:title) if show_title? %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/order/_jobs_fields.html.erb
<p><%= text_field_tag "[#{i}]job" %> => <%= text_field_tag "[#{i}]dependency" %></p>

app/views/order/result.html.erb
<h1>Result</h1>

<% if @output.is_a?(String) %>
    <%= @output %>
<% else %>
<table>
  <tr>
    <th>Job</th>
    <th>Dependency</th>
  </tr>
    <% for out in @output do %>
        <tr>
          <td><%= out[0] %></td>
          <td><%= out[1] %></td>
        </tr>
    <% end %>
</table>

<% end %>

<p><%= link_to 'Back to start', gstart_path %></p>

app/views/order/start.html.erb
<%= form_tag :result, :method => :post do %>
<h1>Enter jobs</h1><h2>and dependencies</h2>
<fieldset>
  <% i = 0 %>
  <% 6.times do %>
      <% i += 1 %>
    <%= render 'jobs_fields', :i => i %>
  <% end %>
  <%= submit_tag 'Submit' %>
</fieldset>
<% end %>